// Shared helpers for the contract tests: the committed OpenAPI contract, the generator and the recorded fixtures.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

/** Same header the `openapi-typescript` CLI writes (and `npm run api:types` commits). */
export const GENERATED_HEADER =
  "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";

export const CONTRACT_PATH = resolve(
  process.cwd(),
  process.env.OPENAPI_CONTRACT_PATH ?? "../specs/003-catalog-api/contracts/openapi.yaml",
);
export const COMMITTED_TYPES_PATH = resolve(process.cwd(), "src/lib/api/schema.gen.ts");

export async function generateTypes(source: string | object): Promise<string> {
  const ast = await openapiTS(source as Parameters<typeof openapiTS>[0]);
  return GENERATED_HEADER + astToString(ast);
}

export function readContract(): string {
  return readFileSync(CONTRACT_PATH, "utf8");
}

export function readCommittedTypes(): string {
  return readFileSync(COMMITTED_TYPES_PATH, "utf8");
}

/** First differing line of two texts, for a readable failure message. */
export function firstDifference(a: string, b: string): string {
  const x = a.split("\n");
  const y = b.split("\n");
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    if (x[i] !== y[i]) return `line ${i + 1}: committed ${JSON.stringify(x[i])} vs generated ${JSON.stringify(y[i])}`;
  }
  return "no difference";
}

export const FIXTURE_NAMES = [
  "clinic",
  "clinic-rules",
  "departments",
  "doctors",
  "lab-test-categories",
  "lab-tests",
  "health-packages",
] as const;
export type FixtureName = (typeof FIXTURE_NAMES)[number];

export function readApiFixture(name: FixtureName): unknown {
  return JSON.parse(readFileSync(resolve(process.cwd(), "tests/fixtures/api", `${name}.json`), "utf8"));
}
