/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness (no database access, not rate limited) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (database reachable, migrations at head) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinic settings (white-label) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        "Cache-Control": components["headers"]["CacheControl"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClinicSettings"];
                    };
                };
                304: components["responses"]["NotModified"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinic/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active clinic rules in display order */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClinicRulePage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Department by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List doctors */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Department slug; unknown slug gives an empty page */
                    department?: components["schemas"]["Slug"];
                    /** @description Case-insensitive contains; % and _ are literal */
                    q?: components["parameters"]["q"];
                    /** @description Doctors with at least one session on this weekday */
                    day?: components["schemas"]["Weekday"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DoctorPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor by slug, with weekly schedule */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Doctor"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-test-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab test categories in display order */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTestCategoryPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lab tests */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Case-insensitive contains; % and _ are literal */
                    q?: components["parameters"]["q"];
                    /** @description Category slug; unknown slug gives an empty page */
                    category?: components["schemas"]["Slug"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTestPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-tests/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab test by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTest"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List health packages */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthPackagePage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-packages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health package by slug, with included tests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthPackageDetail"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available slots for one doctor, per clinic day, within the booking window */
        get: {
            parameters: {
                query?: {
                    /** @description First clinic-local date (default today; earlier dates are clamped to today) */
                    from?: string;
                    /** @description Number of days (default and maximum = clinic booking window) */
                    days?: number;
                };
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (Cache-Control no-store) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DoctorSlots"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book one slot (idempotent) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                    "X-Proxy-Secret": string;
                    "X-Client-IP"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppointmentCreate"];
                };
            };
            responses: {
                /** @description Booked */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentView"];
                    };
                };
                /** @description request_rejected (generic; trap field filled) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description forbidden (missing or wrong proxy secret) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description slot_taken (lost the race or overlapping booking) | slot_unavailable (past, inside lead time, leave, holiday, outside window, off-grid) | booking_limit_reached (max active bookings for this mobile) | idempotency_key_reused (same key, different details). alternatives is present for slot_taken and slot_unavailable. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingConflict"];
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Masked confirmation view by booking reference (rate limited per IP) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 10 Crockford base32 characters; case-insensitive; one dash allowed */
                    reference: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (Cache-Control no-store) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentView"];
                    };
                };
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ends any presented session first (fixation). Limits per IP (429 rate_limited) and per typed email (429 account_locked). */
        post: operations["adminSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/demo/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a 2-hour read-only demo session for today's Karachi date. Ends any presented session first. */
        post: operations["adminDemoStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminSignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ends all of the staff member's sessions and issues a fresh one. */
        post: operations["adminChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lookups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminLookups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A read sent as POST so personal search terms never appear in a URL (FR-021). Default = today, all doctors, all statuses. */
        post: operations["adminBookingSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminBookingDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{reference}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminBookingChangeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{reference}/status/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminBookingUndoStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{reference}/reveal-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff → audit row booking.phone_revealed (reference only). Demo → synthetic number, nothing stored. */
        post: operations["adminBookingRevealPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/doctors-today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminDoctorsToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminStaffList"];
        put?: never;
        post: operations["adminStaffCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{staffId}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminStaffResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{staffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change role and/or active flag. Deactivation ends all sessions. Refuses to leave zero active admins (409 last_admin). */
        patch: operations["adminStaffUpdate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Slug: string;
        /** @enum {string} */
        Weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
        HHMM: string;
        /** Format: uuid */
        Uuid: string;
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "not_found" | "method_not_allowed" | "validation_error" | "rate_limited" | "internal_error" | "service_unavailable" | "not_configured";
                message: string;
                requestId: string;
                details?: {
                    field: string;
                    issue: string;
                }[];
            };
        };
        ImageAsset: {
            src: string;
            alt: string;
            width: number;
            height: number;
        };
        PhoneNumber: {
            display: string;
            tel: string;
        };
        OpeningHoursRule: {
            days: components["schemas"]["Weekday"][];
            opens: components["schemas"]["HHMM"];
            closes: components["schemas"]["HHMM"];
        };
        ClinicSettings: {
            name: string;
            tagline: string;
            fullTitle: string;
            demoNotice: string;
            emergencyPhone: components["schemas"]["PhoneNumber"];
            generalPhone: components["schemas"]["PhoneNumber"];
            address: string[];
            /** @example Asia/Karachi */
            timeZone: string;
            openingHours: components["schemas"]["OpeningHoursRule"][];
            labHours: components["schemas"]["OpeningHoursRule"][];
            mapArea: {
                bbox: number[];
                label: string;
            };
            credit: {
                text: string;
                /** Format: uri */
                href: string;
            };
            indexable: boolean;
            isSample: boolean;
            logo: components["schemas"]["ImageAsset"];
            brandColors: {
                primary: string;
                accent: string;
            };
        };
        ClinicRule: {
            id: components["schemas"]["Uuid"];
            sortOrder: number;
            text: string;
            isSample: boolean;
        };
        Department: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            summary: string;
            image: components["schemas"]["ImageAsset"];
            sortOrder: number;
            overview: string;
            conditions: string[];
            services: string[];
            relatedTestSlugs: components["schemas"]["Slug"][];
            isSample: boolean;
        };
        ScheduleSession: {
            day: components["schemas"]["Weekday"];
            start: components["schemas"]["HHMM"];
            end: components["schemas"]["HHMM"];
            /** @description additive */
            slotMinutes: number;
        };
        Doctor: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            fullName: string;
            departmentId: components["schemas"]["Uuid"];
            specialty: string;
            photo: components["schemas"]["ImageAsset"];
            feePkr: number;
            qualifications: string[];
            experienceYears: number;
            languages: ("Urdu" | "English" | "Sindhi" | "Punjabi")[];
            bio: string;
            /** @description Included in list items too (the list page shows available days) */
            schedule: components["schemas"]["ScheduleSession"][];
            isFeatured: boolean;
            isSample: boolean;
        };
        LabTestCategory: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            iconName: string;
        };
        LabTest: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            alsoKnownAs: string[];
            categoryId: components["schemas"]["Uuid"];
            pricePkr: number;
            sampleType: string;
            reportTime: string;
            preparation: string;
            homeCollection: boolean;
            about: string;
            relatedDepartmentIds: components["schemas"]["Uuid"][];
            isSample: boolean;
        };
        LabTestSummary: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            pricePkr: number;
            homeCollection: boolean;
        };
        HealthPackage: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            iconName: string;
            whoFor: string;
            testSlugs: components["schemas"]["Slug"][];
            packagePricePkr: number;
            preparation: string;
            homeCollection: boolean;
            isSample: boolean;
        };
        HealthPackageDetail: components["schemas"]["HealthPackage"] & {
            /** @description additive; same order as testSlugs */
            tests: components["schemas"]["LabTestSummary"][];
        };
        PageMeta: {
            total: number;
            page: number;
            pageSize: number;
        };
        ClinicRulePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["ClinicRule"][];
        };
        LabTestCategoryPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["LabTestCategory"][];
        };
        DepartmentPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Department"][];
        };
        DoctorPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Doctor"][];
        };
        LabTestPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["LabTest"][];
        };
        HealthPackagePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["HealthPackage"][];
        };
        ErrorInfo: {
            /** @enum {string} */
            code: "not_found" | "method_not_allowed" | "validation_error" | "rate_limited" | "internal_error" | "service_unavailable" | "not_configured" | "forbidden" | "request_rejected" | "slot_taken" | "slot_unavailable" | "booking_limit_reached" | "idempotency_key_reused" | "not_signed_in" | "session_expired" | "sign_in_failed" | "account_locked" | "csrf_failed" | "demo_read_only" | "password_change_required" | "weak_password" | "email_taken" | "last_admin" | "transition_not_allowed" | "booking_changed" | "undo_unavailable";
            message: string;
            requestId: string;
            retryAfterSeconds?: number;
            details?: {
                field: string;
                issue: string;
            }[];
        };
        Slot: {
            /**
             * Format: date-time
             * @description UTC instant
             */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            localTime: string;
        };
        AlternativeSlot: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string;
        };
        SlotDay: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
            /** @enum {string} */
            status: "available" | "fully_booked" | "doctor_unavailable" | "clinic_closed" | "not_working" | "no_longer_available";
            /** @description Only when status is clinic_closed */
            holidayName?: string;
            /** @description Available slots only */
            slots: components["schemas"]["Slot"][];
        };
        DoctorSlots: {
            doctorSlug: string;
            timeZone: string;
            windowDays: number;
            /** Format: date-time */
            generatedAt: string;
            days: components["schemas"]["SlotDay"][];
        };
        AppointmentCreate: {
            doctorSlug: string;
            /** Format: date-time */
            startsAt: string;
            fullName: string;
            /** @description Pakistani mobile; normalized to +923XXXXXXXXX */
            mobile: string;
            email?: string | null;
            reason?: string | null;
            /** @constant */
            acceptRules: true;
            /** @description Honeypot; must be empty */
            trap?: string | null;
        };
        AppointmentView: {
            /** @description Display form XXXXX-XXXXX */
            reference: string;
            /** @enum {string} */
            status: "confirmed" | "cancelled" | "completed";
            doctor: {
                slug: string;
                fullName: string;
                specialty: string;
            };
            department: {
                slug: string;
                name: string;
            };
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string;
            timeZone: string;
            feePkr: number;
            /** @example A**** K**** */
            patientNameMasked: string;
            /** @example 0300****567 */
            mobileMasked: string;
            /**
             * Format: date-time
             * @description When the booking was made
             */
            bookedAt: string;
            isSample: boolean;
        };
        BookingConflict: {
            error: components["schemas"]["ErrorInfo"];
            alternatives?: components["schemas"]["AlternativeSlot"][];
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** @enum {string} */
        Role: "admin" | "receptionist";
        /** @enum {string} */
        BookingStatus: "confirmed" | "arrived" | "completed" | "no_show" | "cancelled";
        Viewer: {
            /** @enum {string} */
            kind: "staff" | "demo";
            /** @description staff only */
            role?: components["schemas"]["Role"];
            displayName?: string;
            mustChangePassword?: boolean;
            csrfToken: string;
            /**
             * Format: date
             * @description staff: today in clinic time; demo: the session's demo date
             */
            clinicToday: string;
            /** @example Asia/Karachi */
            timezone: string;
            /**
             * Format: date-time
             * @description earlier of idle and absolute expiry
             */
            sessionExpiresAt?: string;
        };
        SignInRequest: {
            email: string;
            password: string;
        };
        /** @description Returned to the website server only. The BFF moves `token` into the cookie and strips it from the browser response. */
        SessionIssued: {
            token: string;
            viewer: components["schemas"]["Viewer"];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        Trend: {
            value: number | null;
            previous: number | null;
            delta: number | null;
            /** Format: date */
            comparedTo: string;
        };
        Overview: {
            /** Format: date */
            localDate: string;
            /** Format: date-time */
            now: string;
            /** @description holiday name when closed */
            clinicClosed?: string | null;
            kpis: {
                appointments: components["schemas"]["Trend"];
                arrived: components["schemas"]["Trend"];
                completed: components["schemas"]["Trend"];
                noShows: components["schemas"]["Trend"];
                cancellations: components["schemas"]["Trend"];
                utilisationPct: components["schemas"]["Trend"];
            };
            agenda: {
                doctor: components["schemas"]["DoctorRef"];
                items: components["schemas"]["BookingSummary"][];
            }[];
            nextUp: components["schemas"]["BookingSummary"][];
            /** @description The most recently created bookings (any appointment date), newest first (FR-042). The client polls this endpoint every 30 s (FR-041) and shows a notification for each item whose bookedAt is later than the newest it has already seen; on first load it only records the newest bookedAt. Demo: always empty (the browser simulates new bookings itself). */
            recentBookings?: (components["schemas"]["BookingSummary"] & {
                /** Format: date-time */
                bookedAt: string;
            })[];
            isSample: boolean;
        };
        DoctorRef: {
            /** Format: uuid */
            id: string;
            name: string;
            departmentName: string;
            isActive?: boolean;
        };
        BookingSummary: {
            reference: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string;
            status: components["schemas"]["BookingStatus"];
            version: number;
            /** @example Ayesha K. */
            patientNameMasked: string;
            /** @example 0300****567 */
            phoneMasked: string;
            doctor: components["schemas"]["DoctorRef"];
            /** @description server-computed with the clock (FR-023/024) */
            allowedNext: components["schemas"]["BookingStatus"][];
            isSample?: boolean;
        };
        BookingDetail: components["schemas"]["BookingSummary"] & {
            patientName: string;
            emailMasked?: string | null;
            reason?: string | null;
            /** @description Pediatrics (demo sample data): the child's age */
            patientAge?: number;
            /** @description Pediatrics (demo sample data): mother or father */
            bookedBy?: string;
            feePkr: number;
            /** Format: date-time */
            bookedAt: string;
            history: {
                /** Format: date-time */
                at: string;
                fromStatus?: components["schemas"]["BookingStatus"] | null;
                toStatus: components["schemas"]["BookingStatus"];
                /** @description staff display name or 'Online booking' */
                actor: string;
                isUndo: boolean;
            }[];
        };
        BookingSearchRequest: {
            /** @description reference or patient name; never logged */
            q?: string;
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** Format: uuid */
            doctorId?: string;
            /** Format: uuid */
            departmentId?: string;
            statuses?: components["schemas"]["BookingStatus"][];
            /** @default 1 */
            page: number;
        };
        BookingPage: {
            items: components["schemas"]["BookingSummary"][];
            total: number;
            /** @description bookings per status for the same filters, ignoring the status filter (the chips) */
            statusCounts?: {
                [key: string]: number;
            };
            page: number;
            /** @constant */
            pageSize: 20;
        };
        StatusChangeRequest: {
            to: components["schemas"]["BookingStatus"];
            expectedVersion: number;
        };
        StatusChangeResult: {
            booking: components["schemas"]["BookingDetail"];
            /** Format: uuid */
            changeId: string;
            /** Format: date-time */
            undoExpiresAt: string;
        };
        UndoRequest: {
            /** Format: uuid */
            changeId: string;
        };
        BookingChanged: {
            error: components["schemas"]["ErrorInfo"];
            latest?: components["schemas"]["BookingDetail"];
        };
        PhoneReveal: {
            /** @example 0300 1234567 */
            phone: string;
            telHref: string;
            /** @constant */
            maskAfterSeconds: 60;
        };
        Insights: {
            /** @enum {integer} */
            rangeDays: 7 | 30 | 90;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            total: number;
            perDay: {
                /** Format: date */
                date: string;
                count: number;
            }[];
            byDepartment: {
                departmentName: string;
                count: number;
                cancelled: number;
            }[];
            byStatus: {
                status: components["schemas"]["BookingStatus"];
                count: number;
            }[];
            byHour: {
                hour: number;
                count: number;
            }[];
            isSample: boolean;
        };
        DoctorsToday: {
            /** Format: date */
            localDate: string;
            clinicClosed?: string | null;
            working: {
                doctor: components["schemas"]["DoctorRef"];
                sessions: {
                    start?: string;
                    end?: string;
                }[];
                scheduled: number;
                booked: number;
                free: number;
                freePassed?: number;
                utilisationPct: number;
                /** @description local HH:MM */
                nextFree?: string | null;
            }[];
            onLeave: components["schemas"]["DoctorRef"][];
            notIn: components["schemas"]["DoctorRef"][];
        };
        ActivityEvent: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            at: string;
            action: string;
            outcome: string;
            actorName?: string | null;
            actorRole?: string | null;
            bookingReference?: string | null;
            fromStatus?: string | null;
            toStatus?: string | null;
            /** @description first 6 chars of the keyed IP fingerprint */
            networkTag?: string;
            isSample?: boolean;
        };
        ActivityPage: {
            items: components["schemas"]["ActivityEvent"][];
            total: number;
            page: number;
            pageSize: number;
        };
        Staff: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
            /** @description Sample staff only: the role title shown on the demo staff list. */
            jobTitle?: string;
            role: components["schemas"]["Role"];
            isActive: boolean;
            mustChangePassword?: boolean;
            /** Format: date-time */
            lastSignInAt?: string | null;
            isSample?: boolean;
        };
        StaffCreate: {
            email: string;
            displayName: string;
            role: components["schemas"]["Role"];
            temporaryPassword: string;
        };
        Lookups: {
            doctors: components["schemas"]["DoctorRef"][];
            departments: {
                /** Format: uuid */
                id: string;
                name: string;
                isActive?: boolean;
            }[];
        };
    };
    responses: {
        /** @description If-None-Match matched; no body */
        NotModified: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unknown or inactive slug */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid parameter */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests from this IP */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Database unreachable (service_unavailable) or clinic not configured (not_configured) */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 401 not_signed_in / session_expired */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 403 forbidden / demo_read_only / password_change_required / csrf_failed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 409 (see code) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BookingChanged"];
            };
        };
        /** @description 422 validation_error / weak_password */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 429 rate_limited / account_locked (Retry-After header) */
        AdminRateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        page: number;
        pageSize: number;
        /** @description Case-insensitive contains; % and _ are literal */
        q: string;
        slug: components["schemas"]["Slug"];
        /** @description Booking reference without dash (Crockford base32). */
        Reference: string;
    };
    requestBodies: never;
    headers: {
        /** @description Weak ETag on every catalog 200 */
        ETag: string;
        /** @description Cache-Control on every catalog 200 */
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            /** @description sign_in_failed (generic) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
            429: components["responses"]["AdminRateLimited"];
        };
    };
    adminDemoStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description demo session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["AdminRateLimited"];
        };
    };
    adminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current viewer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Viewer"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    adminSignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description new session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    adminLookups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description filter options incl. inactive records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lookups"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description today at a glance; polled every 30 s while visible (FR-041) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminBookingSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingSearchRequest"];
            };
        };
        responses: {
            /** @description page of bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    adminBookingDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking reference without dash (Crockford base32). */
                reference: components["parameters"]["Reference"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description detail (phone and email masked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminBookingChangeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking reference without dash (Crockford base32). */
                reference: components["parameters"]["Reference"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeRequest"];
            };
        };
        responses: {
            /** @description changed (booking + status history + audit in one transaction) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusChangeResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    adminBookingUndoStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking reference without dash (Crockford base32). */
                reference: components["parameters"]["Reference"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndoRequest"];
            };
        };
        responses: {
            /** @description restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description undo_unavailable / slot_taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingChanged"];
                };
            };
        };
    };
    adminBookingRevealPhone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking reference without dash (Crockford base32). */
                reference: components["parameters"]["Reference"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description full phone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneReveal"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminInsights: {
        parameters: {
            query: {
                range: 7 | 30 | 90;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description charts data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insights"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    adminDoctorsToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description who is in today */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorsToday"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminActivity: {
        parameters: {
            query?: {
                action?: string;
                staffId?: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description newest first (demo → synthetic feed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminStaffList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description staff accounts (demo → synthetic) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminStaffCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            /** @description created (must change password at first sign-in) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description email_taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Validation"];
        };
    };
    adminStaffResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staffId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    temporaryPassword: string;
                };
            };
        };
        responses: {
            /** @description reset; all of that person's sessions ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Validation"];
        };
    };
    adminStaffUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staffId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role?: components["schemas"]["Role"];
                    isActive?: boolean;
                };
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description not_found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description last_admin */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
