/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness (no database access, not rate limited) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (database reachable, migrations at head) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinic settings (white-label) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        "Cache-Control": components["headers"]["CacheControl"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClinicSettings"];
                    };
                };
                304: components["responses"]["NotModified"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinic/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active clinic rules in display order */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClinicRulePage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Department by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Department"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List doctors */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Department slug; unknown slug gives an empty page */
                    department?: components["schemas"]["Slug"];
                    /** @description Case-insensitive contains; % and _ are literal */
                    q?: components["parameters"]["q"];
                    /** @description Doctors with at least one session on this weekday */
                    day?: components["schemas"]["Weekday"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DoctorPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor by slug, with weekly schedule */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Doctor"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-test-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab test categories in display order */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTestCategoryPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lab tests */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                    /** @description Case-insensitive contains; % and _ are literal */
                    q?: components["parameters"]["q"];
                    /** @description Category slug; unknown slug gives an empty page */
                    category?: components["schemas"]["Slug"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTestPage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab-tests/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab test by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabTest"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List health packages */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    pageSize?: components["parameters"]["pageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthPackagePage"];
                    };
                };
                304: components["responses"]["NotModified"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-packages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health package by slug, with included tests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthPackageDetail"];
                    };
                };
                304: components["responses"]["NotModified"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctors/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available slots for one doctor, per clinic day, within the booking window */
        get: {
            parameters: {
                query?: {
                    /** @description First clinic-local date (default today; earlier dates are clamped to today) */
                    from?: string;
                    /** @description Number of days (default and maximum = clinic booking window) */
                    days?: number;
                };
                header?: never;
                path: {
                    slug: components["parameters"]["slug"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (Cache-Control no-store) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DoctorSlots"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book one slot (idempotent) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                    "X-Proxy-Secret": string;
                    "X-Client-IP"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppointmentCreate"];
                };
            };
            responses: {
                /** @description Booked */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentView"];
                    };
                };
                /** @description request_rejected (generic; trap field filled) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description forbidden (missing or wrong proxy secret) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description slot_taken (lost the race or overlapping booking) | slot_unavailable (past, inside lead time, leave, holiday, outside window, off-grid) | booking_limit_reached (max active bookings for this mobile) | idempotency_key_reused (same key, different details). alternatives is present for slot_taken and slot_unavailable. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingConflict"];
                    };
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Masked confirmation view by booking reference (rate limited per IP) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 10 Crockford base32 characters; case-insensitive; one dash allowed */
                    reference: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (Cache-Control no-store) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppointmentView"];
                    };
                };
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Slug: string;
        /** @enum {string} */
        Weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
        HHMM: string;
        /** Format: uuid */
        Uuid: string;
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "not_found" | "method_not_allowed" | "validation_error" | "rate_limited" | "internal_error" | "service_unavailable" | "not_configured";
                message: string;
                requestId: string;
                details?: {
                    field: string;
                    issue: string;
                }[];
            };
        };
        ImageAsset: {
            src: string;
            alt: string;
            width: number;
            height: number;
        };
        PhoneNumber: {
            display: string;
            tel: string;
        };
        OpeningHoursRule: {
            days: components["schemas"]["Weekday"][];
            opens: components["schemas"]["HHMM"];
            closes: components["schemas"]["HHMM"];
        };
        ClinicSettings: {
            name: string;
            tagline: string;
            fullTitle: string;
            demoNotice: string;
            emergencyPhone: components["schemas"]["PhoneNumber"];
            generalPhone: components["schemas"]["PhoneNumber"];
            address: string[];
            /** @example Asia/Karachi */
            timeZone: string;
            openingHours: components["schemas"]["OpeningHoursRule"][];
            labHours: components["schemas"]["OpeningHoursRule"][];
            mapArea: {
                bbox: number[];
                label: string;
            };
            credit: {
                text: string;
                /** Format: uri */
                href: string;
            };
            indexable: boolean;
            isSample: boolean;
            logo: components["schemas"]["ImageAsset"];
            brandColors: {
                primary: string;
                accent: string;
            };
        };
        ClinicRule: {
            id: components["schemas"]["Uuid"];
            sortOrder: number;
            text: string;
            isSample: boolean;
        };
        Department: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            summary: string;
            image: components["schemas"]["ImageAsset"];
            sortOrder: number;
            overview: string;
            conditions: string[];
            services: string[];
            relatedTestSlugs: components["schemas"]["Slug"][];
            isSample: boolean;
        };
        ScheduleSession: {
            day: components["schemas"]["Weekday"];
            start: components["schemas"]["HHMM"];
            end: components["schemas"]["HHMM"];
            /** @description additive */
            slotMinutes: number;
        };
        Doctor: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            fullName: string;
            departmentId: components["schemas"]["Uuid"];
            specialty: string;
            photo: components["schemas"]["ImageAsset"];
            feePkr: number;
            qualifications: string[];
            experienceYears: number;
            languages: ("Urdu" | "English" | "Sindhi" | "Punjabi")[];
            bio: string;
            /** @description Included in list items too (the list page shows available days) */
            schedule: components["schemas"]["ScheduleSession"][];
            isFeatured: boolean;
            isSample: boolean;
        };
        LabTestCategory: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            iconName: string;
        };
        LabTest: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            alsoKnownAs: string[];
            categoryId: components["schemas"]["Uuid"];
            pricePkr: number;
            sampleType: string;
            reportTime: string;
            preparation: string;
            homeCollection: boolean;
            about: string;
            relatedDepartmentIds: components["schemas"]["Uuid"][];
            isSample: boolean;
        };
        LabTestSummary: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            pricePkr: number;
            homeCollection: boolean;
        };
        HealthPackage: {
            id: components["schemas"]["Uuid"];
            slug: components["schemas"]["Slug"];
            name: string;
            iconName: string;
            whoFor: string;
            testSlugs: components["schemas"]["Slug"][];
            packagePricePkr: number;
            preparation: string;
            homeCollection: boolean;
            isSample: boolean;
        };
        HealthPackageDetail: components["schemas"]["HealthPackage"] & {
            /** @description additive; same order as testSlugs */
            tests: components["schemas"]["LabTestSummary"][];
        };
        PageMeta: {
            total: number;
            page: number;
            pageSize: number;
        };
        ClinicRulePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["ClinicRule"][];
        };
        LabTestCategoryPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["LabTestCategory"][];
        };
        DepartmentPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Department"][];
        };
        DoctorPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Doctor"][];
        };
        LabTestPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["LabTest"][];
        };
        HealthPackagePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["HealthPackage"][];
        };
        ErrorInfo: {
            /** @enum {string} */
            code: "not_found" | "method_not_allowed" | "validation_error" | "rate_limited" | "internal_error" | "service_unavailable" | "not_configured" | "forbidden" | "request_rejected" | "slot_taken" | "slot_unavailable" | "booking_limit_reached" | "idempotency_key_reused";
            message: string;
            requestId: string;
            details?: {
                field: string;
                issue: string;
            }[];
        };
        Slot: {
            /**
             * Format: date-time
             * @description UTC instant
             */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            localTime: string;
        };
        AlternativeSlot: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string;
        };
        SlotDay: {
            /** Format: date */
            date: string;
            /** @enum {string} */
            weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
            /** @enum {string} */
            status: "available" | "fully_booked" | "doctor_unavailable" | "clinic_closed" | "not_working" | "no_longer_available";
            /** @description Only when status is clinic_closed */
            holidayName?: string;
            /** @description Available slots only */
            slots: components["schemas"]["Slot"][];
        };
        DoctorSlots: {
            doctorSlug: string;
            timeZone: string;
            windowDays: number;
            /** Format: date-time */
            generatedAt: string;
            days: components["schemas"]["SlotDay"][];
        };
        AppointmentCreate: {
            doctorSlug: string;
            /** Format: date-time */
            startsAt: string;
            fullName: string;
            /** @description Pakistani mobile; normalized to +923XXXXXXXXX */
            mobile: string;
            email?: string | null;
            reason?: string | null;
            /** @constant */
            acceptRules: true;
            /** @description Honeypot; must be empty */
            trap?: string | null;
        };
        AppointmentView: {
            /** @description Display form XXXXX-XXXXX */
            reference: string;
            /** @enum {string} */
            status: "confirmed" | "cancelled" | "completed";
            doctor: {
                slug: string;
                fullName: string;
                specialty: string;
            };
            department: {
                slug: string;
                name: string;
            };
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string;
            timeZone: string;
            feePkr: number;
            /** @example A**** K**** */
            patientNameMasked: string;
            /** @example 0300****567 */
            mobileMasked: string;
            isSample: boolean;
        };
        BookingConflict: {
            error: components["schemas"]["ErrorInfo"];
            alternatives?: components["schemas"]["AlternativeSlot"][];
        };
    };
    responses: {
        /** @description If-None-Match matched; no body */
        NotModified: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unknown or inactive slug */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid parameter */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests from this IP */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Database unreachable (service_unavailable) or clinic not configured (not_configured) */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        page: number;
        pageSize: number;
        /** @description Case-insensitive contains; % and _ are literal */
        q: string;
        slug: components["schemas"]["Slug"];
    };
    requestBodies: never;
    headers: {
        /** @description Weak ETag on every catalog 200 */
        ETag: string;
        /** @description Cache-Control on every catalog 200 */
        CacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
